# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPDyU4yTiXpGYTzJrmJ6WiKybWrUuWtk
"""
import csv


class HotelManager:

    """ Clase Hotelmanager"""
    def __init__(self, file_path):
        """ Inicializar clase cargar parh"""
        self.file_path = file_path

    def crear_hotel(self, idh, nombre, direccion, habs):
        """ Metodo crear hotel"""
        with open(self.file_path, 'a', newline='', encoding='utf-8') as file:
            writer = csv.writer(file)
            writer.writerow([idh, nombre, direccion] + habs)

    def borrar_hotel(self, idh):
        """ Metodo borrar hotel"""
        with open(self.file_path, 'r', encoding='utf-8') as file:
            lines = file.readlines()
        with open(self.file_path, 'w', encoding='utf-8') as file:
            writer = csv.writer(file)
            encontrado = False
            for line in lines:
                if line.split(',')[0] != idh:
                    writer.writerow(line.strip().split(','))
                else:
                    encontrado = True
            if not encontrado:
                print("Hotel no encontrado.")

    def actualizar_hotel(self, idh, nuevo_nombre, nueva_direccion):
        """ Metodo actualizar hotel"""
        hotel_encontrado = False
        with open(self.file_path, 'r', encoding='utf-8') as file:
            lines = file.readlines()
        with open(self.file_path, 'w', encoding='utf-8') as file:
            writer = csv.writer(file)
            for line in lines:
                print(line.split(',')[0])
                if line.split(',')[0] == idh:
                    writer.writerow(
                      [idh, nuevo_nombre, nueva_direccion, line.split(',')[3],
                       line.split(',')[4], line.split(',')[5]]
                       )
                    hotel_encontrado = True
                else:
                    writer.writerow(line.strip().split(','))
        if not hotel_encontrado:
            print("Hotel no encontrado.")

    def consultar_hoteles(self):
        """ Metodo consultar hotel"""
        with open(self.file_path, 'r', encoding='utf-8') as file:
            reader = csv.reader(file)
            hoteles = list(reader)
        return hoteles

    def reserva_habitacion(self, idh, hab):
        """ Metodo reservar habitacion"""
        encontrado = False
        disponible = False
        with open(self.file_path, 'r', encoding='utf-8') as file:
            lines = file.readlines()
        with open(self.file_path, 'w', encoding='utf-8') as file:
            writer = csv.writer(file)
            for line in lines:
                if line.split(',')[0] == idh:
                    encontrado = True
                    if line.split(',')[2 + int(hab)] == "0":
                        if hab == 1:
                            writer.writerow(
                             [idh,  line.split(',')[1],  line.split(',')[2],
                              1, line.split(',')[4],
                              line.split(',')[5]]
                             )
                        if hab == 2:
                            writer.writerow(
                             [idh,  line.split(',')[1],  line.split(',')[2],
                              line.split(',')[3], 1,
                              line.split(',')[5]]
                             )
                        if hab == 3:
                            writer.writerow(
                             [idh,  line.split(',')[1],  line.split(',')[2],
                              line.split(',')[3],
                              line.split(',')[4], 1]
                             )
                        disponible = True
                        print("Habitacion reservada.")
                    else:
                        writer.writerow(line.strip().split(','))
                        disponible = False
                else:
                    writer.writerow(line.strip().split(','))
            if not disponible:
                print("Habitacion no disponible.")
            if not encontrado:
                print("Hotel no encontrado para reserva.")
