# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fPDyU4yTiXpGYTzJrmJ6WiKybWrUuWtk
"""

import unittest
import os
from customer import Mcustomer

class TestcustManager(unittest.TestCase):
    def setUp(self):
        # Crea un archivo de prueba para las pruebas
        self.file_path = 'test_customer.csv'
        self.manager = Mcustomer(self.file_path)

    def tearDown(self):
    # Elimina el archivo de prueba después de las pruebas
      if os.path.exists(self.file_path):
        os.remove(self.file_path)

    def test_crear_customer(self):
        # Verifica que se pueda crear un customer
        
        self.manager.crear_customer("10", "Juan Gonzalez", "juan@hotmail.com", "3232323")
        cust = self.manager.consultar_customer()
        self.assertIn(["10", "Juan Gonzalez", "juan@hotmail.com", "3232323"], cust)

    def test_actualizar_customer(self):
        # Verifica que se pueda actualizar un customer correctamente
        
        self.manager.crear_customer("20", "Maria Gonzalez", "maria@hotmail.com", "3232323")
        self.manager.actualizar_customer("20", "mariannn@hotmail.com", "33342323")
        cust = self.manager.consultar_customer()
        self.assertIn(["20", "Maria Gonzalez", "mariannn@hotmail.com", "33342323"], cust)

    def test_borrar_customer(self):
        # Verifica que se pueda borrar un customer correctamente
        
        self.manager.crear_customer("30", "Jesus Gonzalez", "jesus@hotmail.com", "3232323")
        self.manager.borrar_customer("30")
        cust = self.manager.consultar_customer()
        self.assertNotIn(["30", "Jesus Gonzalez", "jesus@hotmail.com", "3232323"], cust)
    
if __name__ == '__main__':
    unittest.main()