# -*- coding: utf-8 -*-
"""

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z8LUFAuBY31dJEalwKqSzzrdh7ZkbSqV
"""

# -*- coding: utf-8 -*-
"""Clase testreserva
"""

import unittest
import os
from reserva import Reserva

class TestresManager(unittest.TestCase):
    def setUp(self):
        # Crea un archivo de prueba para las pruebas
       
        self.clientes_file = "customers.csv"
        self.hoteles_file = "hoteles.csv"
        self.reservas_file = "reservas.csv"
        self.manager = Reserva(self.clientes_file, self.hoteles_file, self.reservas_file)

    def tearDown(self):
    # Elimina el archivo de prueba después de las pruebas
      if os.path.exists(self.reservas_file):
        os.remove(self.reservas_file)

    def test_crear_reserva(self):
        # Verifica que se pueda crear una reserva

        self.manager.realizar_reserva("10", "1000", "1")
        cust = self.manager.consultar_reservas()
        self.assertIn(["10", "1000", "1"], cust)

    def test_cancelar_reserva(self):
        # Verifica que se pueda cancelar una reserva
        self.manager.cancelar_reserva("10", "1000", "1")
        cust = self.manager.consultar_reservas()
        self.assertNotIn(["10", "1000", "1"], cust)
   
if __name__ == '__main__':
    unittest.main()